### PR TITLE
added playsinline setting for HTML5 player on iOS.

### PR DESCRIPTION
**Pull request by t-yokota**
I added "playsinline" setting to the player object for avoiding fullscreen playback on iOS.
Please check it.

### CODE REVIEW

**Comment by qurihara** [comment]
Merged. Thanks!

**Comment by t-yokota** [comment]
Thank you for merging!
Could you deploy this update to "srtjs.azurewebsites.net" ?

**Comment by qurihara** [comment]
Done.
Thank you for reminding me.
I forgot many things about this project, including why I'm using Azure instead of Github pages to host it...

**Comment by t-yokota** [comment]
Thank you for deploying it after some years...
I checked it works properly!

**Pull request merged**
